- NEWS.md
- tests/testthat/test-abnormal.R
- tests/testthat/test-abnormal_by_baseline.R
- tests/testthat/test-abnormal_by_marked.R
- tests/testthat/test-abnormal_by_worst_grade.R
- tests/testthat/test-abnormal_by_worst_grade_worsen.R
- tests/testthat/test-estimate_incidence_rate.R
- tests/testthat/test-formats.R
- tests/testthat/test-h_format_row.R
- tests/testthat/test-h_response_biomarkers_subgroups.R
- tests/testthat/test-h_survival_biomarkers_subgroups.R
- tests/testthat/test-h_survival_duration_subgroups.R
- tests/testthat/test-logistic_regression.R
- tests/testthat/test-prune_occurrences.R
- tests/testthat/test-response_subgroups.R
- tests/testthat/test-rtables_access.R
- tests/testthat/test-split_cols_by_groups.R
- tests/testthat/test-summarize_ancova.R
- tests/testthat/test-summarize_change.R
- tests/testthat/test-summarize_patients_exposure_in_cols.R
- tests/testthat/test-survival_coxph_pairwise.R
- tests/testthat/test-survival_duration_subgroups.R
- tests/testthat/test-survival_time.R
- tests/testthat/test-survival_timepoint.R
- tests/testthat/test-table_lgrt02.R
- tests/testthat/test-test_proportion_diff.R
- tests/testthat/test-utils.R
- tests/testthat/test-utils_factor.R
> 613 Remove `tern:::` prefix from tern tests

- R/abnormal_by_baseline.R
- R/coxph.R
- R/decorate_grob.R
- R/g_forest.R
- R/h_response_subgroups.R
- R/h_survival_duration_subgroups.R
- R/prop_diff.R
- R/utils_checkmate.R
- R/utils_factor.R
- R/utils_grid.R
- man/assertions.Rd
- tests/testthat/setup-skip_if_too_deep.R
> 608 checkmate no stopifnot@main

- DESCRIPTION
- README.md
Part of https://github.com/insightsengineering/teal/issues/668
> update installation instructions

- tests/testthat/test-h_survival_biomarkers_subgroups.R
> 673 Fix `h_survival_biomarkers_subgroups` tests

- tests/testthat/test-h_response_biomarkers_subgroups.R
> 672 Fix `h_response_biomarkers_subgroups` tests

- NEWS.md
- R/h_stack_by_baskets.R
- tests/testthat/test-h_stack_by_baskets.R
> 683 fix test var labels changes@main

- NEWS.md
- R/abnormal_by_worst_grade.R
Closes #692
Closes https://github.com/insightsengineering/sme-tasks/issues/413
> 692 Fix count_abnormal_by_worst_grade PARAM bug

- DESCRIPTION
> 705 Fix `nestcolor` CRAN check note

- NEWS.md
- tests/testthat/test-estimate_proportion.R
- tests/testthat/test-prop_diff.R
> Add tests for `prop_strat_wilson` and `prop_diff_strat_nc`

- NEWS.md
- R/kaplan_meier_plot.R
- man/g_km.Rd
- man/h_decompose_gg.Rd
- man/h_ggkm.Rd
- man/h_grob_tbl_at_risk.Rd
- man/h_grob_y_annot.Rd
- man/h_km_layout.Rd
- man/kaplan_meier.Rd
> 711 Add footnotes parameter to `g_km`

- R/prop_diff.R
Needed for https://github.com/insightsengineering/teal.modules.clinical/issues/586
> 586 Fill empty weights for `prop_diff_strat_nc`

- NEWS.md
@edelarua do you think we should group better the NAMESPACE polishing and the checkmate stuff? (the second one I think it is much clearer atm). 
Fixes #717
> Clean `NEWS.md`

- NEWS.md
- R/summarize_ancova.R
Closes #725 
Closes https://github.com/insightsengineering/coredev-tasks/issues/395
> 725 Fix `h_ancova` bug

- staged_dependencies.yaml
adding downstream tern.gee dependency
> adding tern.gee to staged.deps

- NEWS.md
- R/wrap_text.R
> added deprecated badge

- staged_dependencies.yaml
> citril dep

- DESCRIPTION
- NEWS.md
- R/summarize_glm_count.R
> add warning for negative binomial. Increase test coverage.

- tests/testthat/test-summarize_glm_count.R
> Adding test to improve code coverage.

- R/summarize_glm_count.R
Closes #744 
See [R CMD check line 77](https://github.com/insightsengineering/tern/actions/runs/3603704788/jobs/6072226587#step:13:78) where NOTE previously occurred.
> 744 Fix `h_glm_negbin` note

- NEWS.md
- R/summarize_ancova.R
- tests/testthat/test-summarize_ancova.R
> update conf_level passing in s_ancova

- NEWS.md
- R/summarize_num_patients.R
- man/summarize_num_patients.Rd
- tests/testthat/test-summarize_num_patients.R
> Add option to remove `(n)` suffix in `s_num_patients`

- NEWS.md
- R/kaplan_meier_plot.R
- man/g_km.Rd
- man/kaplan_meier.Rd
Please check that formulas for median/minimum follow-up time are correct when reviewing.
Closes #792
> Add options to annotate `g_km` with statistics/vertical lines

- staged_dependencies.yaml
> updated rtables staged dep

- DESCRIPTION
> update version from rtables and formatters

- NEWS.md
- R/utils_rtables.R
- man/add_rowcounts.Rd
- man/c_label_n.Rd
- tests/testthat/_snaps/utils_rtables.md
- tests/testthat/test-utils_rtables.R
Closes #842 
Closes https://github.com/insightsengineering/chevron/issues/414
> Fix bug in `add_rowcounts`

- DESCRIPTION
- NEWS.md
> [skip vbump] replacing version from 0.8.0 to 0.8.1

- .Rbuildignore
- .gitignore
- NEWS.md
Fixes #20
Let me know if there is something to order differently or remove @edelarua @shajoezhu @cicdguy
*I removed `man-roxygen` after Emily's work
> Organization of ignores

- NEWS.md
- R/argument_convention.R
- R/summarize_variables.R
- man/argument_convention.Rd
- man/compare_variables.Rd
- man/count_cumulative.Rd
- man/count_missed_doses.Rd
- man/count_occurrences.Rd
- man/count_occurrences_by_grade.Rd
- man/count_patients_with_event.Rd
- man/estimate_multinomial_rsp.Rd
- man/estimate_proportions.Rd
- man/incidence_rate.Rd
- man/odds_ratio.Rd
- man/prop_diff.Rd
- man/prop_diff_test.Rd
- man/summarize_ancova.Rd
- man/summarize_glm_count.Rd
- man/summarize_num_patients.Rd
- man/summarize_variables.Rd
- man/survival_coxph_pairwise.Rd
- man/survival_time.Rd
- man/survival_timepoint.Rd
> fixing argument convention and adding section_div to summarize_vars

- DESCRIPTION
> Fix GRAN build errors

- NEWS.md
- R/estimate_multinomial_rsp.R
- tests/testthat/_snaps/estimate_multinom_rsp.md
> Update level order in `d_onco_rsp_label`

- DESCRIPTION
- NEWS.md
- README.md
> Release v0.8.2 [skip vbump]

- NEWS.md
- R/kaplan_meier_plot.R
> Add zero counts to `g_km` annotation table

- NEWS.md
- R/g_lineplot.R
> Fix `NA` value bug in `g_lineplot`

- NEWS.md
- R/logistic_regression.R
- man/tidy.glm.Rd
> fix formals for `tern:::tidy.glm`

- NEWS.md
- R/kaplan_meier_plot.R
- man/g_km.Rd
- man/h_grob_coxph.Rd
- man/h_grob_median_surv.Rd
> Improve annotation scaling in `g_km`

- NEWS.md
- R/kaplan_meier_plot.R
> Improve error message in `g_km` for single arm when annot_coxph=TRUE

- NEWS.md
- R/count_patients_with_flags.R
- man/count_patients_with_flags.Rd
- tests/testthat/_snaps/count_patients_with_flags.md
- tests/testthat/test-count_patients_with_flags.R
No breaking changes in TLG-C or chevron.
Closes #910
> Enable more flexible labelling in `count_patients_with_flags`

- NEWS.md
- R/argument_convention.R
- man/analyze_variables.Rd
- man/argument_convention.Rd
- man/c_label_n.Rd
- man/count_missed_doses.Rd
- man/count_occurrences.Rd
- man/count_occurrences_by_grade.Rd
- man/count_patients_with_event.Rd
- man/count_patients_with_flags.Rd
- man/count_values_funs.Rd
- man/estimate_multinomial_rsp.Rd
- man/summarize_num_patients.Rd
- man/summarize_patients_exposure_in_cols.Rd
> Correct swapped descriptions of `.N_col` and `.N_row` parameters

- R/summarize_coxreg.R
- tests/testthat/test-summarize_coxreg.R
Closes #1016 and https://github.com/insightsengineering/rtables/issues/701#
> Fix degenerate table warning in `summarize_coxreg`

- staged_dependencies.yaml
test with https://github.com/openpharma/staged.dependencies/pull/182
> update staged deps config

- DESCRIPTION
> update rtables and formatters versions

- DESCRIPTION
- NEWS.md
- R/prop_diff_test.R
- R/summarize_glm_count.R
- R/utils_checkmate.R
- inst/REFERENCES.bib
- man/assertions.Rd
- man/h_glm_count.Rd
- man/h_prop_diff_test.Rd
> change version to 0.9.0, [skip vbump]

- NEWS.md
- R/g_forest.R
- inst/WORDLIST
- man/g_forest.Rd
> Close #1026: Expose gpar to control graphic settings in g_forest.

- NEWS.md
- R/kaplan_meier_plot.R
- man/g_km.Rd
- man/h_grob_tbl_at_risk.Rd
- man/h_km_layout.Rd
- tests/testthat/_snaps/g_km/g-km-at-risk-title.svg
- tests/testthat/test-g_km.R
Closes #1064 
Not sure if this text is to be independent of the table or not but placement/formatting is easy to change.
> Add "Patients at Risk" title for `g_km` at risk annotation table

- DESCRIPTION
- NEWS.md
- tests/testthat/_snaps/summarize_glm_count.md
- tests/testthat/test-summarize_glm_count.R
- tests/testthat/test-utils_default_stats_formats_labels.R
> [skip vbump] release v0.9.1

- R/abnormal_by_worst_grade.R
- R/g_lineplot.R
> remove `USUBJID` hard coding

- R/decorate_grob.R
- R/desctools_binom_diff.R
- R/response_subgroups.R
- R/utils_default_stats_formats_labels.R
- data-raw/generate_tern_data.Rmd
- tests/testthat/test-abnormal_by_marked.R
> Fix all lint

- DESCRIPTION
- NEWS.md
> [skip vbump] Release Candidate 0.9.2

- R/g_lineplot.R
- man/g_lineplot.Rd
Part of https://github.com/insightsengineering/teal.modules.clinical/issues/350
> Improve documentation of `whiskers` param in `g_lineplot`

- NEWS.md
- R/g_lineplot.R
- tests/testthat/_snaps/g_lineplot/g-lineplot-cohorts.svg
- tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.svg
- tests/testthat/_snaps/g_lineplot/g-lineplot.svg
Fixes https://github.com/insightsengineering/tlg-catalog/issues/143 https://github.com/insightsengineering/tlg-catalog/discussions/141
> Remove extra y-axis padding in `g_lineplot`

- DESCRIPTION
- tests/testthat/test-utils_ggplot.R
> Add `svglite` to Suggests

- NEWS.md
- R/summarize_ancova.R
- tests/testthat/_snaps/summarize_ancova.md
- tests/testthat/test-summarize_ancova.R
> Fix irregular arm levels calculation bug in `s_ancova`

- NEWS.md
- R/count_occurrences_by_grade.R
- man/count_occurrences_by_grade.Rd
- man/h_append_grade_groups.Rd
- tests/testthat/_snaps/count_occurrences_by_grade.md
- tests/testthat/test-count_occurrences_by_grade.R
> Add option `grade_groups_only` to `count_occurrences_by_grade`

- .pre-commit-config.yaml
- DESCRIPTION
- R/bland_altman.R
- man/extreme_format.Rd
- man/format_auto.Rd
- man/format_count_fraction.Rd
- man/format_count_fraction_fixed_dp.Rd
- man/format_count_fraction_lt10.Rd
- man/format_extreme_values.Rd
- man/format_extreme_values_ci.Rd
- man/format_fraction.Rd
- man/format_fraction_fixed_dp.Rd
- man/format_fraction_threshold.Rd
- man/format_sigfig.Rd
- man/format_xx.Rd
- man/formatting_functions.Rd
I had issues with running pre-commit due to bioc packages but those are not needed at all!
> fix roxygenise deps; styler

- DESCRIPTION
- man/tern-package.Rd
Part of https://github.com/insightsengineering/coredev-tasks/issues/506
> Fix pkgdown redirect

- R/utils_default_stats_formats_labels.R
> Accept `NULL` to `get_labels_from_stats`

- R/decorate_grob.R
- tests/testthat/test-g_forest.R
- tests/testthat/test-g_km.R
- tests/testthat/test-g_lineplot.R
- tests/testthat/test-g_step.R
- tests/testthat/test-g_waterfall.R
- tests/testthat/test-h_km.R
- tests/testthat/test-utils.R
- tests/testthat/test-utils_ggplot.R
> Add tests for functions with missing coverage

- DESCRIPTION
- README.md
> Truetype pagination PR check

- .github/workflows/scheduled.yaml
this uses the following PRs in other repos:
- https://github.com/insightsengineering/verdepcheck/pull/49
- https://github.com/insightsengineering/r-verdepcheck-action/pull/20
- https://github.com/insightsengineering/r.pkg.template/pull/244
> use extra_deps parameter

- DESCRIPTION
- NEWS.md
- R/count_cumulative.R
- man/d_count_cumulative.Rd
> Fixing parameters' defaults for `d_count_cumulative`

- DESCRIPTION
- R/prune_occurrences.R
- man/prune_occurrences.Rd
> Fix typo in `has_fraction_in_any_col` example

- R/utils_default_stats_formats_labels.R
- tests/testthat/_snaps/decorate_grob/deco_grob_text_wrap.svg
- tests/testthat/_snaps/g_km/g_km_at_risk_title.svg
- tests/testthat/_snaps/g_km/g_km_ci_ribbon.svg
- tests/testthat/_snaps/g_km/g_km_crop_ylim.svg
- tests/testthat/_snaps/g_km/g_km_crop_ylim_failure.svg
- tests/testthat/_snaps/g_km/g_km_custom.svg
- tests/testthat/_snaps/g_km/g_km_custom_ylim.svg
- tests/testthat/_snaps/g_km/g_km_default.svg
- tests/testthat/_snaps/g_km/g_km_plot_only.svg
- tests/testthat/_snaps/g_km/g_km_ref_group_coxph.svg
- tests/testthat/_snaps/g_km/g_km_title_footer.svg
- tests/testthat/test-utils_default_stats_formats_labels.R
Fixes #1271 
Also updates outdated graph snaps
> Fix `get_labels_from_stats` test

- DESCRIPTION
> Update DESCRIPTION emmeans to 1.10.4

- R/summarize_glm_count.R
- man/summarize_glm_count.Rd
- tests/testthat/_snaps/summarize_glm_count.md
- tests/testthat/test-summarize_glm_count.R
> adding offset to nb

- DESCRIPTION
- NEWS.md
- R/utils_default_stats_formats_labels.R
- inst/WORDLIST
- man/default_stats_formats_labels.Rd
- man/tern-package.Rd
- tern.Rproj
> v0.9.8 Release [skip vbump]
