insightsengineering/tern

NEWS.md, R/coxph.R, tests/testthat/test-summarize_ancova.R
=> 694 fix stats ancova old versions@main

NEWS.md, R/count_occurrences_by_grade.R
=> 713 `summarize_occurrences_by_grade` missing numeric grades bug

R/g_lineplot.R, tests/testthat/test-g_lineplot.R
=> Reintroducing tests for `g_lineplot` 

.Rbuildignore, R/argument_convention.R, R/compare_variables.R, R/decorate_grob.R, R/estimate_proportion.R, R/g_waterfall.R, R/prop_diff.R, R/summarize_colvars.R, R/summarize_variables.R, man-roxygen/author_liaoc10.R, man-roxygen/author_manukyae.R, man-roxygen/author_qit3.R, man-roxygen/author_song24.R, man-roxygen/author_stoilovs.R, man-roxygen/author_waddella.R, man-roxygen/author_wangh107.R, man-roxygen/author_zhanc107.R, man-roxygen/formatting_arguments.R, man-roxygen/param_is_event.R, man-roxygen/return_rtable.R, man/analyze_vars_in_cols.Rd, man/argument_convention.Rd, man/compare_variables.Rd, man/summarize_colvars.Rd, man/summarize_variables.Rd
=> Use `argument_convention` instead of templates

tests/testthat/_snaps/abnormal_by_worst_grade_worsen.md, tests/testthat/_snaps/h_map_for_count_abnormal.md, tests/testthat/_snaps/h_stack_by_baskets.md, tests/testthat/_snaps/split_cols_by_groups.md, tests/testthat/test-abnormal_by_worst_grade_worsen.R, tests/testthat/test-h_map_for_count_abnormal.R, tests/testthat/test-h_stack_by_baskets.R, tests/testthat/test-split_cols_by_groups.R
Converted most snapshot `tibble`s to `data.frame`s. Replaced 2 unnecessary `tibble` snapshots with different tests.
Closes #866
=> Fix tibble snapshots

DESCRIPTION, staged_dependencies.yaml
=> alphabetical order of staged.deps + biomarker-catalog

NEWS.md, R/coxph.R, _pkgdown.yml, man/pairwise.Rd, tests/testthat/_snaps/coxph.md, tests/testthat/test-coxph.R
Fixes #899 
@danielinteractive fyi. If this function name is anyway needed we can make it an alias as it is identical to `univariate` in the source code
=> deprecating `pairwise`

NEWS.md, R/prop_diff.R, man/prop_diff.Rd, tests/testthat/_snaps/summarize_coxreg.md
=> Add more informative error to `s_proportion_diff`

tests/testthat/_snaps/summarize_ancova.md, tests/testthat/test-summarize_ancova.R, tests/testthat/test-summarize_num_patients.R
=> fixing both validation errors

NEWS.md, R/summarize_coxreg.R, tests/testthat/test-summarize_coxreg.R
Closes #952 
In the univariate no interaction case covariates are now printed in data rows so that pagination can be applied. No change to other cases. Tested all scenarios with pagination and all are now working.
=> Update `summarize_coxreg` to work with pagination in all cases

NEWS.md, R/abnormal_by_baseline.R, tests/testthat/_snaps/abnormal_by_baseline.md
I could not find a reason why this text was initially included so I think we are fine to remove it.
Closes #947
=> Remove "baseline status" text from abnormal by baseline labels

tern.Rproj
I think this is the minimum that can be done. I am not sure if CI does check it already with `--as-cran` but, eventually, it is a fast fix, right @cicdguy?
Fixes #887
=> add `--as-cran` to local proj checks

NEWS.md, R/kaplan_meier_plot.R, man/g_km.Rd, man/h_ggkm.Rd
=> Add `ylim` argument to `g_km`

staged_dependencies.yaml
To fix following
```r
staged.dependencies::dependency_table(
project = "insightsengineering/tern@https://github.com",
project_type = "repo@host",
ref = "main",
verbose = 1
)
```
This branch fixes a problem
```r
staged.dependencies::dependency_table(
project = "insightsengineering/tern@https://github.com",
project_type = "repo@host",
ref = "remove_staged_deps_link@main",
verbose = 1
)
```
=> tlg-catalog no longer contains staged.dependencies.

DESCRIPTION, NEWS.md
=> update news vbump to 0.8.5, [skip vbump]

DESCRIPTION, R/kaplan_meier_plot.R, man/g_km.Rd, man/h_ggkm.Rd, tests/testthat/_snaps/g_km/g-km-crop-ylim.svg, tests/testthat/_snaps/g_km/g-km-custom-ylim.svg, tests/testthat/test-g_km.R
=> Update default `g_km` y limits

NEWS.md, R/analyze_vars_in_cols.R, tests/testthat/_snaps/analyze_vars_in_cols.md, tests/testthat/test-analyze_vars_in_cols.R
FIxes #1013 but it may be not the best way. Last test show an alternative way that is much simpler.
=> Ugly fix for categorical data

DESCRIPTION, NEWS.md, R/analyze_variables.R, R/compare_variables.R, tests/testthat/test-analyze_variables.R, tests/testthat/test-compare_variables.R
Fixes #1033 
@BFalquet can I ask you to check if eventually this would work with your old function?
Nevermind, added the tests from previous version with expect_warning
=> deprecate_warn instead of stop for create_afun*

NEWS.md, R/count_occurrences_by_grade.R, tests/testthat/_snaps/count_occurrences_by_grade.md, tests/testthat/test-count_occurrences_by_grade.R
=> Correct ordering of grade levels in `s_count_occurences_by_grade`

NEWS.md, R/response_subgroups.R
Closes #1038 
Sanitation checks now passing for ONCT05. No changes to table layout/test output.
=> Refactor `tabulate_rsp_subgroups` to pass sanitation checks

tests/testthat/_snaps/utils_default_stats_formats_labels.md, tests/testthat/test-summarize_glm_count.R, tests/testthat/test-utils_default_stats_formats_labels.R
Fixes #1058 
The error comes ONLY from integration tests (mismatch of output rates and rate CI in `h_ppmeans()`). @ayogasekaram tested on docker image, @edelarua and I tested it (I think window-based rstudio and Ubuntu rstudio-server) and there are no differences in our snapshots, i.e. it is passing for all of us. Now I think this needs to come from `stats::predict` step in `h_ppmeans` as also rates are different. It seems we tested everything (adding random seed does not change my local snapshots). Could it have something to do with the system libraries? what do you think @cicdguy? If we cannot fix it, and it is not a fundamental feature we might want to turn it off. Is this function used in the biomarker catalog  @danielinteractive? To my knowledge, it is not used in the TLG-c, right …
=> Fix snapshot differences (it may need muting `h_ppmeans()`)

NEWS.md, R/kaplan_meier_plot.R
Fixes insightsengineering/teal.modules.clinical#837
=> Fix `g_km` unit conversion bug

NEWS.md, R/analyze_vars_in_cols.R, tests/testthat/test-analyze_vars_in_cols.R
=> Update `analyze_vars _in_cols` to allow non-numeric nominal timepoint variable

tests/testthat/test-compare_variables.R, tests/testthat/test-odds_ratio.R, tests/testthat/test-prop_diff.R, tests/testthat/test-split_cols_by_groups.R, tests/testthat/test-summarize_glm_count.R, tests/testthat/test-test_proportion_diff.R
=> Fix integrations tests after `ref_group` update

NEWS.md, R/kaplan_meier_plot.R, man/g_km.Rd, man/h_tbl_coxph_pairwise.Rd, tests/testthat/_snaps/g_km/g-km-ref-group-coxph.svg, tests/testthat/_snaps/kaplan_meier_plot.md, tests/testthat/test-g_km.R
=> Add option to set reference arm in `g_km`

NEWS.md, R/g_lineplot.R, tests/testthat/_snaps/g_lineplot/g-lineplot-cohorts.svg, tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.svg
=> Vertically align plot with table in `g_lineplot`

tests/testthat/test-utils_ggplot.R
Fixes #1150 
The `svglite` package is required to output test snapshots that use `ggsave`.
=> Fix `ggsave` tests

R/g_lineplot.R
follow-up on https://github.com/insightsengineering/tern/pull/1153
Integration test warns for chevron:
```
── Warning ('test-mng01.R:18:3'): mng01 works as expected with custom argument values ──
Graphs cannot be vertically aligned unless the axis parameter is set. Placing graphs unaligned.
Backtrace:
▆
1. └─chevron::mng01_main(...) at test-mng01.R:18:3
2.   └─base::lapply(...)
3.     └─tern (local) FUN(X[[i]], ...)
4.       └─cowplot::plot_grid(p, tbl, ncol = 1, align = "v")
5.         └─cowplot::align_plots(...)
```
It might happen that snapshot test will fail. In such case please kindly provide some help. I have re-run snapshots locally and I got differences for unrelated graphs like KM Plots. This has to do with my local settings. I might be unable to get same graphs like in CI.
=> add axis parameter to plot_grid()

tests/testthat/_snaps/g_lineplot/g-lineplot-cohorts.svg, tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.svg
fix errors reported on ocean integration tests (both valid and nonvalid)
```
✖ | 2       1 | g_lineplot [2.6s]                                               
────────────────────────────────────────────────────────────────────────────────
Failure ('test-g_lineplot.R:27:3'): g_lineplot works with custom settings and statistics table
Snapshot of `testcase` to 'g_lineplot/g-lineplot-w-stats.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.new.svg' to local test directory
* Run `testthat::snapshot_review('g_lineplot/')` to review changes
Backtrace:
1. vdiffr::expect_doppelganger(title = "g_lineplot_w_stats", fig = g_lineplot_w_stats)
at test-g_lineplot.R:27:2
3. testthat::expect_snapshot_file(...)
Failure …
```
=> update g_lineplot snaps

DESCRIPTION, NEWS.md, R/summarize_glm_count.R, man/h_glm_count.Rd, man/summarize_glm_count.Rd, tests/testthat/_snaps/summarize_glm_count.md, tests/testthat/test-summarize_glm_count.R
Close #856 
- Implement `h_glm_negbin()`.
- Add unit tests.
- Update `NEWS.md`.
=> add `h_glm_negbin()`

tests/testthat/setup.R, tests/testthat/test-decorate_grob.R, tests/testthat/test-g_km.R, tests/testthat/test-g_lineplot.R, tests/testthat/test-kaplan_meier_plot.R
=> Fix integration tests

NEWS.md, R/utils_default_stats_formats_labels.R, tests/testthat/_snaps/analyze_variables.md, tests/testthat/_snaps/utils_default_stats_formats_labels.md
=> Update default format for mean p-values

NEWS.md, R/g_lineplot.R, man/g_lineplot.Rd, tests/testthat/_snaps/bland-altman/g_bland_altman.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_cohorts.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_w_stats.svg
=> Fix `g_lineplot` default labels

NEWS.md, R/decorate_grob.R, _pkgdown.yml, man/decorate_grob.Rd, man/decorate_grob_set.Rd, tests/testthat/test-decorate_grob.R
=> Revert deprecation of `decorate_grob`-related functions used by `citril`

R/g_lineplot.R, man/control_lineplot_vars.Rd, man/g_lineplot.Rd, tests/testthat/_snaps/g_lineplot/g_lineplot_cohorts.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_facets.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_w_stats.svg, tests/testthat/test-g_lineplot.R
=> add faceting variable to g_lineplot. add code to maintain factor levels.

DESCRIPTION, NEWS.md, R/utils_ggplot.R, README.md, man/df2gg.Rd
=> [skip vbump], preping for 0.9.4 release

NEWS.md, R/survival_biomarkers_subgroups.R, R/survival_duration_subgroups.R, man/survival_biomarkers_subgroups.Rd, man/survival_duration_subgroups.Rd, tests/testthat/_snaps/survival_biomarkers_subgroups.md, tests/testthat/_snaps/survival_duration_subgroups.md, tests/testthat/test-survival_biomarkers_subgroups.R, tests/testthat/test-survival_duration_subgroups.R
=> Fix documentation for the `label_all` argument of `extract_*` functions

DESCRIPTION, NEWS.md, R/g_lineplot.R, tests/testthat/_snaps/g_lineplot/g_lineplot_factor_levels.svg, tests/testthat/test-g_lineplot.R
update g_lineplot code to handle special characters in group_var. add test for maintaining factor levels.
related to #1212
=> update g_lineplot code to handle special characters

NEWS.md, R/summarize_ancova.R, tests/testthat/_snaps/summarize_ancova.md, tests/testthat/test-summarize_ancova.R
=> Fix bug in `s_ancova` when arm levels include special characters

NEWS.md, R/argument_convention.R, R/g_km.R, R/g_lineplot.R, man/argument_convention.Rd, man/g_km.Rd, man/g_lineplot.Rd, man/h_ggkm.Rd, tests/testthat/_snaps/g_lineplot/g_lineplot_xlim_ylim.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_xticks.svg, tests/testthat/_snaps/g_lineplot/g_lineplot_xticks_by.svg, tests/testthat/test-g_lineplot.R
=> Add `xticks`, `xlim`, and `ylim` arguments to `g_lineplot`

DESCRIPTION, NEWS.md, R/cox_regression.R, R/utils_split_funs.R, man/tidy_coxreg.Rd, man/utils_split_funs.Rd
=> prep for 0.9.5 [skip vbump]

.github/workflows/scheduled.yaml, DESCRIPTION
Part of https://github.com/insightsengineering/coredev-tasks/issues/546
Necessary bump to overcome a lack of binary on ppm snapshots that causes an error on minimum strategies for `scheduled` workflows.
=> Bumps `{rmarkdown}` minimal version

NEWS.md, R/survival_time.R, tests/testthat/test-survival_time.R
- Fixes #1258 
- Use `identical()` instead of `==` to compare integers
- Adds simple test for this issue
- Was not present in some of the older version of `tern`
=> Fixes problem with `a_surv_time` with datasets where "is_event" is always `TRUE`

NEWS.md, R/g_lineplot.R, man/g_lineplot.Rd, tests/testthat/test-g_lineplot.R
Completes #1235 #1236 #1081 and https://github.com/insightsengineering/teal.modules.clinical/issues/1197
=> Update of `g_lineplot` to have line type, error bar width, and avoid empty levels in

NEWS.md, R/g_km.R
Fixes #1279 
Bug reported on Overflow but not able to replicate it.
=> Fix `g_km` bug when multiple estimates are made at max time

NEWS.md, R/analyze_variables.R, R/utils_default_stats_formats_labels.R, tests/testthat/_snaps/analyze_variables.md, tests/testthat/_snaps/compare_variables.md, tests/testthat/_snaps/utils_default_stats_formats_labels.md
Hello,
I wanted to display the count statistic in roughly this format: `xx / xx (xx.xx%)`, but it's impossible to use `analyze_vars` in this manner. I could implement my own `analyze_vars` and the associated functions, but I only need this slight change in the code, and copying the whole thing seems like an overkill.
Let me know if there's a more straightforward solution to display these statistics using the existing API (and not lose the S3 dispatch on different types of input variables).
@shajoezhu @pawelru @gogonzo If you can point me to the correct person to approach regarding this, I'd be grateful.
=> feat: added "fraction" statistic to the "analyze_var_count" method group

vignettes/tables.Rmd, vignettes/tern.Rmd
=> Update NEST site URLs

NEWS.md, R/count_occurrences_by_grade.R, man/count_occurrences_by_grade.Rd, man/try_car_anova.Rd, tests/testthat/_snaps/count_occurrences_by_grade.md, tests/testthat/test-count_occurrences_by_grade.R
=> Refactor `a_count_occurrences_by_grade()`

NEWS.md, R/analyze_variables.R, R/count_values.R, R/summarize_change.R, R/utils_default_stats_formats_labels.R, man/analyze_variables.Rd, man/compare_variables.Rd, man/default_stats_formats_labels.Rd, man/summarize_change.Rd, tests/testthat/_snaps/analyze_variables.md, tests/testthat/_snaps/compare_variables.md, tests/testthat/_snaps/summarize_change.md, tests/testthat/_snaps/utils_default_stats_formats_labels.md, tests/testthat/test-analyze_variables.R
=> refactor geom sd and fix custom stat order

R/abnormal.R, R/abnormal_by_baseline.R, R/abnormal_by_marked.R, R/abnormal_by_worst_grade.R, R/abnormal_lab_worsen_by_baseline.R, R/count_values.R, R/summarize_ancova.R, R/summarize_change.R, R/summarize_glm_count.R
=> Add in missing analysis function option for custom statistics

NEWS.md, R/summarize_ancova.R, man/h_ancova.Rd, man/summarize_ancova.Rd
=> [821] Feature Request: Add weights option to ancova

R/utils_default_stats_formats_labels.R
Fixes #1419 
I think Davide reported this when he first made the function but it was only producing the warning locally at the time.
=> Fix warning from `get_formats_from_stats()`
